version: '3'

services:
  postgre_db:
    container_name: dogtherapy_db
    build: dogtherapy-jpa/
    networks:
      app_network:
        ipv4_address: 172.168.0.102
    expose:
     - "5432" 
  
  dogtherapy_backend:
    container_name: dogtherapy_backend
    build: dogtherapy-war/
    depends_on:
     - postgre_db
    links:
     - postgre_db:db
    expose:
     - "8443"
    networks:
      app_network:
        ipv4_address: 172.168.0.101
        
  dogtherapy_ui:
    container_name: dogtherapy_ui
    build: dogtherapy-ui/
    depends_on:
     - postgre_db
     - dogtherapy_backend
    expose:
     - "8443"
    links:
     - dogtherapy_backend:backend
     - postgre_db:db
    networks:
      app_network:
        ipv4_address: 172.168.0.100

networks:
  app_network:
    driver: bridge
    ipam:
      config:
       - subnet: 172.168.0.0/24