version: '3'
services:
  postgre_db:
    build: dogtherapy-jpa/
    ports:
     - 32777:5432
    container_name: dogotherapy_db
  dogtherapy_backend:
    build: dogtherapy-war/
    ports:
     - 32080:8080
    container_name: dogtherapy_backend
  dogtherapy_ui:
    build: dogtherapy-ui/
    ports:
     - 32081:8080
    container_name: dogtherapy_ui
    
